version: 2.1

orbs:
  slack: circleci/slack@4.12.1
  jq: circleci/jq@2.2.0
  aws-cli: circleci/aws-cli@3.1

jobs:
  build-app:
    docker:
      - image: node:16-alpine3.16
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run: npm install -g typescript
      - run:
          name: Build application
          command: |
            yarn install
            yarn build
      - save_cache:
          paths: [node_modules]
          key: app-build
  lint:
    docker:
      - image: node:16-alpine3.16
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Lint application
          command: |
            yarn lint
  scan:
    docker:
      - image: node:16-alpine3.16
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Scan
          command: |
            yarn audit

  build-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "vite.config.ts"}}
          paths:
            - /caches/bachtn-udacity-05.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/bachtn-udacity-05.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=bachtn-udacity-05 -t bachtn-udacity-05 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/bachtn-udacity-05.tar bachtn-udacity-05
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - /caches/bachtn-udacity-05.tar

  push-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - /caches/bachtn-udacity-05.tar
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/bachtn-udacity-05.tar | true
      - run:
          name: login hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: push images
          command: |
            TAG_VERSION=${CIRCLE_WORKFLOW_ID:0:7}
            docker tag bachtn-udacity-05 abc1zbq/bachtn-udacity-05:latest
            docker tag bachtn-udacity-05 abc1zbq/bachtn-udacity-05:${TAG_VERSION}
            docker push abc1zbq/bachtn-udacity-05:${TAG_VERSION}
            docker push abc1zbq/bachtn-udacity-05:latest
  deploy-eks:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Install depens
          command: |
            apk add curl
            apk add aws-cli
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/bin/kubectl
            apk add helm
      - run:
          name: update kube config
          command: |
            aws eks update-kubeconfig --name $CLUSTER
            kubectl config use $CONTEXT
            echo $(pwd)
            echo $(ls)
      - run:
          name: helm deploy
          command: |
            kubectl create namespace dev || true
            helm upgrade -n dev --install udacity-05 -f ./udacity-05/values.yaml udacity-05 

workflows:

  default:
    jobs:
      - build-app
      - lint:
          requires:
            - build-app
      - scan:
          requires:
            - build-app
      - build-image:
          requires:
            - lint
            - scan
      - push-image:
          requires:
            - build-image
      - deploy-eks:
          requires:
            - push-image
